{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.ijktech",
    "module": "ByteGPT-Android",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "ByteGPT-Android-1.1.0.aar",
          "url": "ByteGPT-Android-1.1.0.aar",
          "size": 61204306,
          "sha512": "aecb68f1100f347ca72417b1ee3166267ddba681596f3d486ac73ea2488aacfc50afdabd8e708c4e68c824573f0a6d542831fc6e18697a009cd1643c2a0fd717",
          "sha256": "a92d9b3914321f2a8f5f4a7438e0ee6010a03a528e7e0489e3b02fdfe2166e82",
          "sha1": "034c63b9e1d8caefb857883c481cc42f417fcb08",
          "md5": "4657f979810a98a637b2a2d9ba524cfd"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.microsoft.onnxruntime",
          "module": "onnxruntime-android",
          "version": {
            "requires": "1.16.3"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "ByteGPT-Android-1.1.0.aar",
          "url": "ByteGPT-Android-1.1.0.aar",
          "size": 61204306,
          "sha512": "aecb68f1100f347ca72417b1ee3166267ddba681596f3d486ac73ea2488aacfc50afdabd8e708c4e68c824573f0a6d542831fc6e18697a009cd1643c2a0fd717",
          "sha256": "a92d9b3914321f2a8f5f4a7438e0ee6010a03a528e7e0489e3b02fdfe2166e82",
          "sha1": "034c63b9e1d8caefb857883c481cc42f417fcb08",
          "md5": "4657f979810a98a637b2a2d9ba524cfd"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ByteGPT-Android-1.1.0-sources.jar",
          "url": "ByteGPT-Android-1.1.0-sources.jar",
          "size": 7541,
          "sha512": "228d09c13f2b0d869ddd8f70d2a1e06e3507a8669bd2da0cb4dc2635db5b50ce4848f7cd45f61835ae5b619aa915f2447a119c6151e16c810c20c3fc84a3986a",
          "sha256": "465ef2976d71cb130adb5acc6439f0bc0daa430fd37d273e951094e9f176ff40",
          "sha1": "584b704212adea7cb3bce1e1f1754cbb097bf30b",
          "md5": "bfd3fc2a4f96e594c15087cf37f7282b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ByteGPT-Android-1.1.0-javadoc.jar",
          "url": "ByteGPT-Android-1.1.0-javadoc.jar",
          "size": 303402,
          "sha512": "5bac97694b6e6ab64c0f3b9bb9948230331555db2ba63d9b620fb19935acc8662fadceb75b38329492cd2cb58d1053e8fbe2ce8b21051835b22effeb5b432a8e",
          "sha256": "07d19a9a08f15a655e0a5507ce53fc35cb055cedd2d25c9c7cd084e784b6814f",
          "sha1": "c9d0db736887c940a6f1daa8ccb8e2e7faa67b73",
          "md5": "08929a6034df41fd4b0a8fd35dbcdfc3"
        }
      ]
    }
  ]
}
